# set prefix key
set -g prefix C-q

# 256 color option
set-option -g default-terminal screen-256color
set-option -ga terminal-overrides ",screen-256color:Tc"

# status bar display format
set -g status-left "#(date +'%H:%M:%S %m/%d')  "
set -g status-left-length=20
set -g status-right="#[fg=colour255,bg=colour27]#{?client_prefix,#[bg=colour208],}Tm "
set -g status-style fg=colour255,bg=colour240

# right alignment window-status
set -g status-justify right

# begin window-index 1
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# Alt + 数字 でウィンドウを切り替える
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

# change window-status appearance
# setw -g window-status-format '#[fg=colour242] #I #W '
set-window-option -g window-status-format "#[fg=colour242] [#I:#{window_panes}] #{b:pane_current_path} "

# on Prefix color change
set-window-option -g window-status-current-format "#[fg=colour255,bg=colour27,bold]#{?window_zoomed_flag,#[bg=colour196],}#{?client_prefix,#[bg=colour208],} [#I:#{window_panes}] #{b:pane_current_path} "

set-window-option -g mode-keys vi

bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

# 新しいPaneを開く場合
bind c new-window -c '#{pane_current_path}'

# 現在のペインでVimが動いているか判定するスクリプト
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|l?n?vim?x?)(diff)?$'"

bind / split-window -h -c '#{pane_current_path}'
bind - split-window -v -c '#{pane_current_path}'
bind -n 'M-/' if-shell "$is_vim" 'send-keys M-/' 'split-window -h -c "#{pane_current_path}"'
bind -n 'M--' if-shell "$is_vim" 'send-keys M--' 'split-window -v -c "#{pane_current_path}"'

bind -n 'M-x' if-shell "$is_vim" 'send-keys M-x' 'confirm-before -p "kill-pane #P? (y/n)" kill-pane'
bind -n 'M-s' if-shell "$is_vim" 'send-keys M-s' 'swap-pane -D'

# show popup window
POPUP_NAME=popup
POPUP_SIZE=98%
bind q if-shell -F '#{==:#{session_name},popup}' {
    detach-client
} {
    display-popup -d "#{pane_current_path}" -w $POPUP_SIZE -h $POPUP_SIZE -E 'tmux attach-session -t $POPUP_NAME || tmux new-session -s $POPUP_NAME'
}

# ==========================================
# vim-tmux-navigator (Alt/Optionキー版)
# ==========================================

# Alt+h/j/k/l で移動（Vimの中ならVimにキーを渡し、そうでないならtmuxのペインを移動）
bind-key -n 'M-h' if-shell "$is_vim" 'send-keys M-h'  'select-pane -L'
bind-key -n 'M-j' if-shell "$is_vim" 'send-keys M-j'  'select-pane -D'
bind-key -n 'M-k' if-shell "$is_vim" 'send-keys M-k'  'select-pane -U'
bind-key -n 'M-l' if-shell "$is_vim" 'send-keys M-l'  'select-pane -R'

# VimとTmuxのシームレスなリサイズ (Ctrl + 矢印キー)
bind -n 'M-H' if-shell "$is_vim" 'send-keys M-H' 'resize-pane -L 2'
bind -n 'M-J' if-shell "$is_vim" 'send-keys M-J' 'resize-pane -D 2'
bind -n 'M-K' if-shell "$is_vim" 'send-keys M-K' 'resize-pane -U 2'
bind -n 'M-L' if-shell "$is_vim" 'send-keys M-L' 'resize-pane -R 2'

# tmuxのバージョンに応じた Alt+\ (前のペインに戻る) の設定
tmux_version='$(tmux -V | sed -En "s/^tmux ([0-9]+(.[0-9]+)?).*/\1/p")'
if-shell -b '[ "$(echo "$tmux_version < 3.0" | bc)" = 1 ]' \
    "bind-key -n 'M-\\' if-shell \"$is_vim\" 'send-keys M-\\'  'select-pane -l'"
if-shell -b '[ "$(echo "$tmux_version >= 3.0" | bc)" = 1 ]' \
    "bind-key -n 'M-\\' if-shell \"$is_vim\" 'send-keys M-\\\\' 'select-pane -l'"

bind -T copy-mode-vi 'v' send -X begin-selection
bind -T copy-mode-vi 'y' send -X copy-selection

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
